### ISSUE TITLE
倒计时问题

### ISSUE THREAD

**Issue by thereqwe** [zhengwenming/CountDown#1]
看代码是倒计时一天,跑起来看是 10:01:40 秒 我是下午2:04分测的

**Comment by zhengwenming** [comment]
你下午14:04测试的，到晚上24:00结束，倒计时的时间就是10个小时啊。不是按整整24个小时算，而是到凌晨00:00结束这样算的。具体的时间你是可以修改代码的，用的时候很多情况是取后台给的时间戳。仔细研究下，有问题可以群里直接联系我479259423。谢谢你的支持，非常感谢。

**Comment by thereqwe** [comment]
非常感谢

**Comment by zhengwenming** [comment]
不客气，代码是经过真实项目锤炼的，可以放心使用。谢谢

**Comment by cloudhm** [comment]
调慢系统时间，内部倒计时计算还是存在，但页面停止了刷新

**Comment by zhengwenming** [comment]
1、谢谢你的反馈。
2、数据是测试的数据，写死的，真实做项目的时候，数据是没次进来页面都从服务器获取。就不存在手机的时间问题了。倒计时是和服务器同步的，即使你调快了手机时间，也不会影响到服务器的。
仅仅是为了演示demo的测试数据。
