### ISSUE TITLE
遍历取出cell问题

### ISSUE THREAD

**Issue by dls007** [zhengwenming/CountDown#4]
我的tableview里面有UITableViewCell 跟自定义cell 一起使用 countDownLabel在自定义cell中 但是如果我混合使用了cell 遍历出来的cell 都是UITableViewCell类型的 
for（countDownCell *cell in cells）｛

｝
再给count down Label 赋值会出现报错 因为取出的都是UITableViewCell类型 说我没有CountDOwnLabel

**Comment by dls007** [comment]
我的tableview里面有UITableViewCell 跟自定义cell 一起使用 countDownLabel在自定义cell中 但是如果我混合使用了cell 遍历出来的cell 都是UITableViewCell类型的 
for（countDownCell *cell in cells）｛

｝
再给count down Label 赋值会出现报错 因为取出的都是UITableViewCell类型 说我没有CountDOwnLabel

**Comment by dls007** [comment]
我的tableview里面有UITableViewCell 跟自定义cell 一起使用 countDownLabel在自定义cell中 但是如果我混合使用了cell 遍历出来的cell 都是UITableViewCell类型的 
for（countDownCell *cell in cells）｛

｝
再给count down Label 赋值会出现报错 因为取出的都是UITableViewCell类型 说我没有CountDOwnLabel

**Comment by dls007** [comment]
我的tableview里面有UITableViewCell 跟自定义cell 一起使用 countDownLabel在自定义cell中 但是如果我混合使用了cell 遍历出来的cell 都是UITableViewCell类型的 
for（countDownCell *cell in cells）｛

｝
再给count down Label 赋值会出现报错 因为取出的都是UITableViewCell类型 说我没有CountDOwnLabel

**Comment by zhengwenming** [comment]
强转一下。
前面加这个 (xxxCell *)，然后就可以了。
